<script type="text/javascript">
document.getElementById('modulo').value = 'categoria';
</script>

<form name="form" method="POST" 
      action="/application/categoria/edit/<?php echo $this->cliente->getId();?>">
	<input type="hidden" name="codigo_categoria" value="<?php echo $this->cliente->getId();?>"/>
	
	<?php 
		$strErros = "";

		if (isset($this->erros["nome"]["isEmpty"])) {
			$strErros .= "\n".$this->erros["nome"]["isEmpty"];
		} elseif (isset($this->erros["nome"]["stringLengthTooShort"])) {
			$strErros .= "\n".$this->erros["nome"]["stringLengthTooShort"];
		} elseif (isset($this->erros["nome"]["stringLengthTooLong"])) {
			$strErros .= "\n".$this->erros["nome"]["stringLengthTooLong"];
		}

		echo $strErros;
	?>
	
	<label>Nome</label>
	<input type="text" name="nome" value="<?php echo $this->cliente->getNome();?>"/>
	<br/>
	<button class="btn btn-success" type="submit">Alterar</button>
</form>