<script type="text/javascript">
document.getElementById('modulo').value = 'categoria';
</script>

<h1>Categorias</h1>
<a href="/application/categoria/create">Cadastrar categoria</a>
<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->clientes as $o): ?>
        <tr>
            <td><?php echo $o->getNome();?></td>    
            <td>
                <a href="/application/categoria/edit/<?php echo $o->getId();?>">
                Editar
                </a>
                |
                <a href="/application/categoria/delete/<?php echo $o->getId();?>">
                Excluir
                </a>
            </td>        
        </tr>
        <?php endforeach;?>
    </tbody>
</table>