<script type="text/javascript">
document.getElementById('modulo').value = 'tecnico';
</script>

<form name="form" method="POST"
      action="/application/tecnico/edit/<?php echo $this->cliente->getId();?>">
	<input type="hidden" name="codigo_tecnico" value="<?php echo $this->cliente->getId();?>"/>
	
	<?php 
		$strErros = "";

		if (isset($this->erros["nome"]["isEmpty"])) {
			$strErros .= "\n".$this->erros["nome"]["isEmpty"];
		} elseif (isset($this->erros["nome"]["stringLengthTooShort"])) {
			$strErros .= "\n".$this->erros["nome"]["stringLengthTooShort"];
		} elseif (isset($this->erros["nome"]["stringLengthTooLong"])) {
			$strErros .= "\n".$this->erros["nome"]["stringLengthTooLong"];
		}

		if (!empty($strErros)) {
			echo "<p>".$strErros."</p>";
		}
	?>
	
	<label>Nome</label>
	<input type="text" name="nome" value="<?php echo $this->cliente->getNome();?>"/>
	<br/>
	<button class="btn btn-success" type="submit">Alterar</button>
</form>