<form name="form" method="POST" action="/application/usuario/login">
	<a href="/application/usuario/create">Cadastrar-se</a>
	<br />
	<br />
	
	<?php
		if (!empty($this->strerro)) {
			echo "<p>".$this->strerro."</p>";
		}
	?>

	<label>Usuario</label>
	<input type="text" name="login" />
	<br/>
	<label>Senha</label>
	<input type="password" name="senha" />
	<br/>
	<button class="btn btn-success" type="submit">Entrar</button>
</form>